#!/usr/bin/env bash
# Remove temporary files generated by cookbook runs.
# Safe to run anytime — only deletes known output patterns, never source files.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "Cleaning cookbook output artifacts..."

# Remove Python cache directories
find "$ROOT/cookbook" -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true
find "$ROOT/cookbook" -name '*.pyc' -delete 2>/dev/null || true

# Remove common output files generated during cookbook runs
find "$ROOT/cookbook" -name '*.log' -not -name 'TEST_LOG.md' -delete 2>/dev/null || true
find "$ROOT/cookbook" -name 'output_*.txt' -delete 2>/dev/null || true
find "$ROOT/cookbook" -name 'temp_*.json' -delete 2>/dev/null || true
find "$ROOT/cookbook" -name '.agent_state' -delete 2>/dev/null || true

echo "Done."
